backend:
  name: git-gateway
  branch: master
  use_graphql: true

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: /assets

collections:
  
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: "date", label: "Post Date", default: "", date_format: "MMMM DD YYYY", picker_utc: true, widget: 'datetime' }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "tag", label: "Tag", widget: "string" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: body, label: Body, widget: markdown }
      - { name: "image", label: "Image", widget: "image"}

  - name: podcasts
    label: Podcasts
    folder: podcasts
    identifier_field: "podcast_title"
    create: true
    fields:
      - { name: "podcast_date", label: "Podcast Date", default: "", date_format: "MMMM DD YYYY", picker_utc: false, widget: 'datetime' }
      - { name: "podcast_title", label: "Podcast Title", widget: "string" }
      - { name: "podcast_description",label: "Podcast Description", widget: "text"}
      - { name: "podcast_url", label: "Podcast URL",  widget: "text"}
      - { name: "podcast_image", label: "Podcast Image", widget: "image"}
    
  - name: coffeeBreak
    label: Coffee Break
    folder: coffeeBreak
    identifier_field: "{{coffeeBreak_title}}"
    create: true
    fields:
      - { name: "coffeeBreak_date", label: "Date", default: "", date_format: "MMMM DD YYYY", picker_utc: false, widget: 'datetime' }
      - { name: "coffeeBreak_title", label: "Title", widget: "string" }
      - { name: "body",label: "Description", widget: "text"}
      - { name: "coffeeBreak_image", label: "Coffee Break Image", widget: "image"}
      - { name: "coffeeBreak_audio", label: "Audio", widget: "file", default: ""}
        